<a href="https://colab.research.google.com/github/siyab8160-max/Data-Science/blob/main/Datasciene_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY :
for faster operations through

Function to create an array
1. a= numpy.array ()

=> pass list , set as argument

=> numpy arrays are also called vectors

2. a = numpy.zeros(shape,dtype=)

3. a = numpy.empty(number of values ,dtype=)

4. a = numpy.full (4,5,datatype=)


In [ ]:
import numpy as np # np is a user defined nickname, alias
# a = alias_name.function
a= np.array([1,3,9,0,2])

# a= numpy.array([])
print (a)

[1 3 9 0 2]


In [ ]:
a = np.array ([1,2,3,'4'])
print(a) # converts all the elements to string

['1' '2' '3' '4']


In [ ]:
#QUESTION 2

np_arr=np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1])) #wherever there is value, boolean conversion will result into true.

a=False
print(bool(a))

a=0
print(bool(a))


True
False


In [ ]:
a= np.zeros(5)
print (a)

b=np.zeros((2,3)) #shape passed as list or tuple
print(b)

c=np.zeros((2,3,4))
print(c)
print(type(c[0][0][0])) #<class 'numpy.float64'>

#to have a specific datatype
d=np.zeros((2,3,4),dtype=int)
print(type(d[0][0][0])) #<class 'numpy.int64'>

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>
<class 'numpy.int64'>


In [ ]:
a = np.empty(4,dtype=int)
print(a) #[ 368611571          0         46 4294967296]

[ 368611571          0         46 4294967296]


In [ ]:
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
a = np.arange(5) # single parameter will be taken as stop
print(a)

b = np.arange(3,12,4,dtype=int) # start,stop,step => exclusive of the stop
print(b)

[0 1 2 3 4]
[ 3  7 11]


In [ ]:
c = np.linspace(5,10,3,dtype=int, endpoint = False) # start, stop, number of values
# here endpoint is included, need to manually turn it to false
print(c)

[5 6 8]


In [ ]:
a = np.ones((2,3),dtype=int)
print(a)

print(np.shape(a)) # tells abput the dimension

print(np.size(a)) # total number of elements

# print(np.dtype(a))

[[1 1 1]
 [1 1 1]]
(2, 3)
6


In [50]:
a = np.random.randint(8,10,5)
print(a)

[9 8 8 9 9]


In [51]:
a = np.random.choice([2,3,5,8],2) # choice from a particular array , passed the list and choosing random values from it
print(a)

[5 3]


BROADCAST

In [60]:
a = np.ones((3,3), dtype = int)
b = np.ones((3,3), dtype = int)
print (a)
print(a*2)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
# elements at corresponding positionn are being operated.

c=np.ones((2,2), dtype=int)
# print(a+c) -> ValueError : operands could not be broadcast together with different shapes

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [61]:
a = [2,3,4]
print(a*2) # prints the list twice 💁🏻‍♀️ 💁🏻‍♀️

[2, 3, 4, 2, 3, 4]


In [68]:
a = np.random.randint(2,15,6)
print(a)
b = a.reshape((3,2))
print(b)

[ 4  3  6 13  5  7]
[[ 4  3]
 [ 6 13]
 [ 5  7]]


In [80]:
a = np.random.randint(2,16,8)
b = a.reshape((2,4))
print(b)

c=b.transpose()
print(c)

a = np.random.randint(2,16,8)
e = a.reshape((2,4))
print(e)

d = np.concatenate((b,e),axis=1) #
print(d)

[[ 7 11  7 14]
 [12  7 10  8]]
[[ 7 12]
 [11  7]
 [ 7 10]
 [14  8]]
[[14 11 15  3]
 [ 5  9  2  4]]
[[ 7 11  7 14 14 11 15  3]
 [12  7 10  8  5  9  2  4]]


In [82]:
a = np.random.randint(2,16,8)
print(a)
b = np.random.randint(2,16,8)
print(b)

c = np.where(b > 2, b, a)
print(c)

[ 3 11 10  9 12 11  7  3]
[ 3 12  6 10 13  5  2  8]
[ 3 12  6 10 13  5  7  8]


In [85]:
a = np.random.randint(2,16,8)
print(a)
b = np.sort(a)
print(b)

[ 2 14 13  8 10  7  6 13]
[ 2  6  7  8 10 13 13 14]


In [86]:
a = np.random.randint(2,16,8)
print(a)
b = np.sum(a)
print(b)

[ 4 11 15 11 15  2  8  5]
71


In [87]:
a = np.random.randint(2,16,8)
print(a)
b = np.mean(a)
print(b)

[ 8  4  7  9 10  4 11  5]
7.25


In [88]:
a = np.random.randint(2,16,8)
print(a)
b = np.std(a) # standard deviation
print(b)

[13  7 14  5  4  8  7  6]
3.391164991562634


In [89]:
a = np.random.randint(2,16,8)
print(a)
b = np.min(a)
print(b)

[13  4 11  4 14  2  8  2]
2


In [90]:
a = np.random.randint(2,16,8)
print(a)
b = np.max(a)
print(b)

[ 3 10  8 13  9  5 15 10]
15


In [91]:
a = np.random.randint(2,16,8)
print(a)
b = np.unique(a)
print(b)

[11 10 13 10  4 13 12 10]
[ 4 10 11 12 13]


In [93]:
a = np.random.randint(2,16,8)
a = a.reshape((2,4))
print(a)

b = np.random.randint(2,16,8)
b = b.reshape((4,2))
print(b)

c = np.matmul(a,b)
print(c)

[[14  3 11 13]
 [ 2 11 15 11]]
[[12  8]
 [ 6  8]
 [12 11]
 [ 8  9]]
[[422 374]
 [358 368]]


In [105]:
scores = input()
# scores = np.random.randint(0,100,7)
scores = scores.split()
# scores =[int(x) for x in scores] -> another way to convert in integer
scores = list(map(int,scores))
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]
scores = np.array(scores)
for i in range (len(scores)):
  print(scores[i],days[i])
print("maximum score : ", np.max(scores), "on ", days[np.argmax(scores)])
print("minimum score : ", np.min(scores), "on ", days[np.argmin(scores)])
print("sum of scores : ", np.sum(scores))
print("mean of scores : ", np.mean(scores))
print("standard deviation of scores", np.std(scores))

100 99 76 0 56 12 34
100 MON
99 TUES
76 WED
0 THURS
56 FRI
12 SAT
34 SUN
maximum score :  100 on  MON
minimum score :  0 on  THURS
sum of scores :  377
mean of scores :  53.857142857142854
standard deviation of scores 37.24217490744511


In [107]:
scores = []
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]

for i in range (7):
  x=input(f'give the input for the {days[i]}: ') #fstring : variables inside a string


In [111]:
#Question 1
a = np.array([3,3,3,3])
b = a
b[0] = 1
a[-1]=6
print(a,b)

[1 3 3 6] [1 3 3 6]
