<a href="https://colab.research.google.com/github/siyab8160-max/Data-Science/blob/main/Data_science_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# a=np.random.randint(1,91,25)
# b=a.reshape((5,5))
b=np.random.randint(1,91,size=(5,5))
print(b)

#row wise mean
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))


# Syntax: np.where(condition, value_if_true, value_if_false) -> forms new matrix
b[b%2==0]=-1
print(b)

c=np.sort(b,axis=0)
print(c)

d=np.sort(b,axis=1)
print(d)

e=np.sum(b,axis=0)
print(e)

f=np.sum(b,axis=1)
print(f)

g=np.count_nonzero(b<0, axis=0)
print(g)

#or
count_col=np.sum(np.where(b<0,1,0),axis=0)
print(count_col)

[[40 59 14 60 29]
 [36 64 10 43  8]
 [23 67 53 43  9]
 [88 23 78 61 34]
 [29 50 30  8 32]]
[43.2 52.6 37.  43.  22.4]
[40.4 32.2 39.  56.8 29.8]
[[-1 59 -1 -1 29]
 [-1 -1 -1 43 -1]
 [23 67 53 43  9]
 [-1 23 -1 61 -1]
 [29 -1 -1 -1 -1]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 23 -1 43 -1]
 [23 59 -1 43  9]
 [29 67 53 61 29]]
[[-1 -1 -1 29 59]
 [-1 -1 -1 -1 43]
 [ 9 23 43 53 67]
 [-1 -1 -1 23 61]
 [-1 -1 -1 -1 29]]
[ 49 147  49 145  35]
[ 85  39 195  81  25]
[3 2 4 2 3]
[3 2 4 2 3]


In [ ]:
import numpy as np
stock = np.random.randint(1,100,size=(5,5))
print(stock)
demand= np.random.randint(1,100,size=(5,5))
print(demand)
stock=stock-demand
print(stock)

total_shortage_daywise = abs(np.sum(np.where(stock<0,stock,0),axis=1))
print(total_shortage_daywise)

stock[stock<0]=0
print(stock)

products_with_zerostock_daywise= np.sum(np.where(stock==0,1,0),axis=1)
print(products_with_zerostock_daywise)

stock=np.sort(stock,axis=1)
print(stock)

[[65 60 17 73 69]
 [48 65 89 41 14]
 [57 68 93 62 45]
 [14 56 11 47 78]
 [18 94 84 37 17]]
[[42 27 97 45 37]
 [72 33 91  8 94]
 [81 25 21 19  4]
 [88 42 74 16  6]
 [11  8 50 98 49]]
[[ 23  33 -80  28  32]
 [-24  32  -2  33 -80]
 [-24  43  72  43  41]
 [-74  14 -63  31  72]
 [  7  86  34 -61 -32]]
[ 80 106  24 137  93]
[[23 33  0 28 32]
 [ 0 32  0 33  0]
 [ 0 43 72 43 41]
 [ 0 14  0 31 72]
 [ 7 86 34  0  0]]
[1 3 1 2 2]
[[ 0 23 28 32 33]
 [ 0  0  0 32 33]
 [ 0 41 43 43 72]
 [ 0  0 14 31 72]
 [ 0  0  7 34 86]]


**PANDAS**

In [12]:
import pandas as pd

file=pd.read_csv("/student_data.csv",sep = ',')
print(file)

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   

In [10]:
print(file.head(8))

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
5                      0            

In [11]:
print(file.tail(10))

      study_hours  attendance  sleep_hours  internet_usage  \
9990            4          72            8               6   
9991           10          93            7              11   
9992            5         100            9               2   
9993           10          86            9               9   
9994            4          53            7               8   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9990                      4              72       86.47           Placed  
9991                      3              53       97.90           Placed  
9992                      9              62      100.00           Placed  
9993             